CREATE TABLE users (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   username VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   role VARCHAR(255) NOT NULL
);

CREATE TABLE applications (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(255),
   category VARCHAR(255),
   description VARCHAR(255),
   developer_id BIGINT NOT NULL,
   archive BLOB NOT NULL,
   archive_name VARCHAR(255),
   picture_small BLOB NOT NULL,
   picture_big BLOB NOT NULL,
   download_count INT NOT NULL DEFAULT 0,
   created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   FOREIGN KEY (developer_id) REFERENCES users(id)
);

CREATE TABLE ratings (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   application_id BIGINT NOT NULL,
   user_id BIGINT NOT NULL,
   rating INT NOT NULL,
   created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   FOREIGN KEY (application_id) REFERENCES applications (id),
   FOREIGN KEY (user_id) REFERENCES users (id)
);