CREATE TABLE applications (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(255),
   category VARCHAR(255),
   description VARCHAR(255),
   developer_id BIGINT NOT NULL,
   archive bytea NOT NULL,
   archive_name VARCHAR(255),
   picture_small bytea NOT NULL,
   picture_big bytea NOT NULL,
   download_count INT NOT NULL DEFAULT 0,
   created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   FOREIGN KEY (developer_id) REFERENCES users(id)
);