CREATE TABLE ratings (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   application_id BIGINT NOT NULL,
   user_id BIGINT NOT NULL,
   rating INT NOT NULL,
   created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   FOREIGN KEY (application_id) REFERENCES applications (id),
   FOREIGN KEY (user_id) REFERENCES users (id)
);